services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      UID: 1000
      GID: 1000
      ENABLE_JMX: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      VIEW_DISTANCE: 4
      EXEC_DIRECTLY: true
      JMX_HOST: 192.168.2.200
      INIT_MEMORY: 1G
      MAX_MEMORY: 5G
      SERVER_NAME: El server jaja
      SERVER_PORT: 25566
      SNOOPER_ENABLED: false
      TYPE: "FORGE"
      VERSION: "1.16.5"
      EULA: "TRUE"
      FORCE_GAMEMODE: true
      MOTD: El \u00a74server\u00a7r jaja \u00a7kXDLOLOSKIBIDI
      ICON: "/home/manu/minecraft/foto.jpeg"
      DIFFICULTY: hard
      MODE: creative
      PVP: true
      ONLINE_MODE: true
    volumes:
      - /home/manu/minecraft/data:/data
